name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=1.14.1
  - pyyaml=5.3.1
  - hydra-core=1.0.6
  - pip=20.3.3
  - pylint=2.9.6
  - autopep8=1.6.0
  - pip:
      - wandb==0.10.31